#!/usr/bin/env python3
"""
gen_isa_doc.py -- build docs/ISA.md from the RTL, never by hand.

An instruction-encoding table written by a person is a copy of something that
lives in the source, and nothing keeps the copy honest -- the stale-anchor
failure this project keeps finding. So every field width, enum value,
capability mask and register length below is parsed out of:

    tt/tile/src/rtl/mom_pkg.sv        descriptor, enums, widths, constants
    tt/tile/src/rtl/mom_param_rom.sv  per-engine capability and cost rows
    tt/tile/src/rtl/hydra_tt_regs.sv  the host register map

Usage:
    python3 tools/gen_isa_doc.py            write docs/ISA.md
    python3 tools/gen_isa_doc.py --check    fail if the committed file differs
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "tt/tile/src/rtl/mom_pkg.sv"
ROM = ROOT / "tt/tile/src/rtl/mom_param_rom.sv"
REGS = ROOT / "tt/tile/src/rtl/hydra_tt_regs.sv"
OUT = ROOT / "docs/ISA.md"


def need(path):
    if not path.exists():
        sys.exit(f"{path} is missing: run ./scripts/setup-tile.sh first")
    return path.read_text()


def enum(text, typename):
    """[(name, value, comment)] for one typedef enum."""
    m = re.search(r"typedef enum logic \[\d+:\d+\] \{([^}]*)\}\s*" + typename, text, re.S)
    if not m:
        sys.exit(f"enum {typename} not found in mom_pkg.sv")
    out = []
    for line in m.group(1).splitlines():
        e = re.match(r"\s*(\w+)\s*=\s*\d+'d(\d+),?\s*(?://\s*(.*))?", line)
        if e:
            out.append((e.group(1), int(e.group(2)), (e.group(3) or "").strip()))
    return out


def struct(text, typename):
    """[(field, width, comment)] for one packed struct, in declaration order."""
    # [^}]* not .*? : the lazy form started at the FIRST struct in the file and
    # ran past its closing brace to the requested name, silently returning the
    # wrong struct's fields.
    m = re.search(r"typedef struct packed \{([^}]*)\}\s*" + typename, text, re.S)
    if not m:
        sys.exit(f"struct {typename} not found")
    out = []
    for line in m.group(1).splitlines():
        f = re.match(r"\s*(?:logic\s*\[(\d+):(\d+)\]|(\w+_e))\s+(\w+);\s*(?://\s*(.*))?", line)
        if f:
            width = int(f.group(1)) - int(f.group(2)) + 1 if f.group(1) else None
            out.append([f.group(4), width, f.group(3), (f.group(5) or "").strip()])
    return out


def enum_width(text, typename):
    m = re.search(r"typedef enum logic \[(\d+):(\d+)\][^}]*\}\s*" + typename, text, re.S)
    return int(m.group(1)) - int(m.group(2)) + 1


def localparam_int(text, name):
    m = re.search(rf"localparam int unsigned {name}\s*=\s*(\d+)", text)
    return int(m.group(1)) if m else None


def param_rows(text):
    rows = {}
    for m in re.finditer(r"localparam logic \[EPARAM_W-1:0\] DEF_(\w+)\s*=\s*\{([^}]+)\}", text):
        vals = [v.strip() for v in m.group(2).split(",")]
        def num(v):
            b = re.match(r"\d+'b([01_]+)", v)
            if b:
                return int(b.group(1).replace("_", ""), 2), b.group(1)
            d = re.match(r"\d+'d(\d+)", v)
            return int(d.group(1)), d.group(1)
        rows[m.group(1)] = [num(v) for v in vals]
    return rows


def reg_map(text):
    addrs = dict(re.findall(r"A_(\w+)\s*=\s*7'h([0-9A-Fa-f]+)", text))
    lens = dict(re.findall(r"A_(\w+):\s*reg_len\s*=\s*5'd(\d+);", text))
    writable = re.search(r"writable = (.*?);", text, re.S).group(1)
    order = sorted(addrs, key=lambda k: int(addrs[k], 16))
    return [(k, int(addrs[k], 16), int(lens.get(k, 0)),
             "RW" if f"A_{k}" in writable else "RO") for k in order]


def main(check=False):
    pkg, rom, regs = need(PKG), need(ROM), need(REGS)
    eng = enum(pkg, "engine_e")
    opc = enum(pkg, "opclass_e")
    dt = enum(pkg, "dtype_e")
    lat = enum(pkg, "lat_hint_e")
    pwr = enum(pkg, "pwr_hint_e")
    wd = struct(pkg, "work_desc_t")
    ep = struct(pkg, "eng_param_t")
    rows = param_rows(rom)
    regmap = reg_map(regs)
    wdw = localparam_int(pkg, "WD_W")
    epw = localparam_int(pkg, "EPARAM_W")
    engn = localparam_int(pkg, "ENG_N")
    costw = localparam_int(pkg, "COST_W")

    L = []
    w = L.append
    w("# Instruction set\n")
    w("GENERATED by `tools/gen_isa_doc.py` from the RTL. Do not edit: run the")
    w("tool. `make isa-check` fails if this file and the sources disagree.\n")
    w("HYDRA-130 has no instruction stream of its own. Work is issued as a")
    w(f"**{wdw}-bit work descriptor** — one descriptor is one instruction — and the")
    w("dispatcher decides which engine executes it. Everything else is")
    w("configuration through the register map at the end of this document.\n")

    # ---- descriptor ------------------------------------------------------
    w("## The work descriptor: the instruction word\n")
    w("Fields are listed most significant first, exactly as `work_desc_t` packs")
    w("them. Bit 127 is the top of `op_class`.\n")
    w("| field | bits | position | meaning |")
    w("|---|---|---|---|")
    hi = wdw - 1
    for name, width, etype, comment in wd:
        if width is None:
            width = {"opclass_e": enum_width(pkg, "opclass_e"),
                     "dtype_e": enum_width(pkg, "dtype_e"),
                     "lat_hint_e": enum_width(pkg, "lat_hint_e"),
                     "pwr_hint_e": enum_width(pkg, "pwr_hint_e")}[etype]
        lo = hi - width + 1
        note = re.sub(r"^\d+\s*", "", comment or "")
        w(f"| `{name}` | {width} | [{hi}:{lo}] | {note} |")
        hi = lo - 1
    w("")
    if hi != -1:
        w(f"**WARNING: fields account for {wdw - hi - 1} of {wdw} bits.**\n")

    # ---- op classes ------------------------------------------------------
    w("## Operation classes (`op_class`)\n")
    w("The class selects the work-volume formula the cost model evaluates; the")
    w("comment is that formula.\n")
    w("| value | name | work volume |")
    w("|---|---|---|")
    for n, v, c in opc:
        w(f"| {v} | `{n}` | {c or ''} |")
    w("")
    w("## Data types (`dtype`)\n")
    w("| value | name | notes |")
    w("|---|---|---|")
    for n, v, c in dt:
        w(f"| {v} | `{n}` | {c or ''} |")
    w("")
    w("## Hints\n")
    w("`lat_hint` biases against setup cost; `pwr_hint` sets the weight on the")
    w("energy term.\n")
    w("| value | lat_hint | meaning |")
    w("|---|---|---|")
    for n, v, c in lat:
        w(f"| {v} | `{n}` | {c or ''} |")
    w("")
    w("| value | pwr_hint | meaning |")
    w("|---|---|---|")
    for n, v, c in pwr:
        w(f"| {v} | `{n}` | {c or ''} |")
    w("")

    # ---- capability matrix ----------------------------------------------
    w("## What each engine can execute\n")
    w(f"{engn} engines. An engine whose mask clears the descriptor's class or")
    w("data type is removed from the selection **before any cost is compared**:")
    w("capability is a hard gate, not a penalty. Masks are bit-per-value,")
    w("least significant bit = value 0.\n")
    w("| engine | | op classes it accepts | data types it accepts |")
    w("|---|---|---|---|")
    key = {"CPU": "ENG_CPU", "SIMD": "ENG_SIMD", "TPU": "ENG_TPU",
           "NTT": "ENG_NTT", "CRYPTO": "ENG_CRYPTO"}
    for n, v, c in eng:
        short = n.replace("ENG_", "")
        r = rows.get(short)
        if not r:
            continue
        opmask = r[5][0]
        dtmask = r[4][0]
        ops = ", ".join(o[0].replace("OPC_", "") for o in opc if opmask >> o[1] & 1)
        dts = ", ".join(d[0].replace("DT_", "") for d in dt if dtmask >> d[1] & 1)
        w(f"| {v} `{short}` | {c or ''} | {ops} | {dts} |")
    w("")
    w("## Engine cost parameters\n")
    w(f"One {epw}-bit row per engine, writable at run time through the `PARAM`")
    w("register — this is what makes the dispatch policy tunable after tapeout.\n")
    w("| field | bits | meaning |")
    w("|---|---|---|")
    hi = epw - 1
    for name, width, _etype, comment in ep:
        if width is None:
            sys.exit(f"eng_param_t field {name} has no explicit width; "
                     "gen_isa_doc.py only parses logic [h:l] fields there")
        lo = hi - width + 1
        w(f"| `{name}` | {width} | [{hi}:{lo}] {comment or ''} |")
        hi = lo - 1
    w("")
    w("Reset values:\n")
    w("| engine | p_peak_log2 | t_setup | bw_bytes_log2 | eps_op | dtype_msk | opc_msk |")
    w("|---|---|---|---|---|---|---|")
    for short in ["CPU", "SIMD", "TPU", "NTT", "CRYPTO"]:
        r = rows.get(short)
        if r:
            w(f"| {short} | {r[0][0]} | {r[1][0]} | {r[2][0]} | {r[3][0]} | "
              f"`{r[4][1]}` | `{r[5][1]}` |")
    w("")
    w(f"Cost is a {costw}-bit cycle count, saturating. The calibration factor")
    w("is Q2.6 per engine and op class, moved by measured completions.\n")

    # ---- register map ----------------------------------------------------
    w("## Host register map\n")
    w("Reached over SPI in the register personality (see README, pin tables).")
    w("Command byte is `{rw, addr[6:0]}`, `rw = 1` reads; data follows, most")
    w("significant byte first; writes commit at chip-select rise and only if")
    w("exactly the right number of bytes arrived.\n")
    w("| addr | name | bytes | access |")
    w("|---|---|---|---|")
    for name, addr, length, acc in regmap:
        w(f"| 0x{addr:02X} | `{name}` | {length} | {acc} |")
    w("")
    w("Unmapped addresses read as zero; writing one sets `FRAME_ERR`.\n")

    text = "\n".join(L)
    if check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"DRIFT: {OUT.relative_to(ROOT)} does not match the RTL. "
                  f"Run: python3 tools/gen_isa_doc.py")
            sys.exit(1)
        print(f"{OUT.relative_to(ROOT)} matches the RTL")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}: {len(L)} lines, "
              f"{len(opc)} op classes, {len(dt)} data types, {len(regmap)} registers")


if __name__ == "__main__":
    main(check="--check" in sys.argv)
