#!/usr/bin/env python3
"""
gen_cpu_isa.py -- docs/ISA_CPU.md from the decoder's own behaviour.

Runs tools/isa/isa_probe_cpu.sv against the real control_unit, reads the CSV
it prints, and maps the numeric enum values back through asicirific_pkg.sv.
Nothing in the output is transcribed by hand, so the table cannot disagree
with the hardware -- it can only be incomplete about the sweep, and the sweep
is in the probe.

Usage:
  python3 tools/isa/gen_cpu_isa.py           write docs/ISA_CPU.md
  python3 tools/isa/gen_cpu_isa.py --check   fail if the file is out of date
"""
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
PKG = ROOT / "engines/cpu/rtl/asicirific_pkg.sv"
CTRL = ROOT / "engines/cpu/rtl/control_unit.sv"
PROBE = ROOT / "tools/isa/isa_probe_cpu.sv"
OUT = ROOT / "docs/ISA_CPU.md"


def enum_names(text, typename):
    m = re.search(r"typedef enum logic \[\d+:\d+\] \{([^}]*)\}\s*" + typename, text, re.S)
    if not m:
        sys.exit(f"enum {typename} not found in {PKG.name}")
    out = {}
    for line in m.group(1).splitlines():
        e = re.match(r"\s*(\w+)\s*=\s*\d+'d(\d+)", line)
        if e:
            out[int(e.group(2))] = e.group(1)
    return out


def run_probe():
    for f in (PKG, CTRL, PROBE):
        if not f.exists():
            sys.exit(f"{f} is missing")
    with tempfile.TemporaryDirectory() as td:
        v = pathlib.Path(td) / "probe.v"
        sim = pathlib.Path(td) / "probe"
        conv = subprocess.run(["sv2v", str(PKG), str(CTRL), str(PROBE)],
                              capture_output=True, text=True)
        if conv.returncode:
            sys.exit("sv2v failed:\n" + conv.stderr[-1500:])
        v.write_text(conv.stdout)
        c = subprocess.run(["iverilog", "-g2012", "-o", str(sim), str(v)],
                           capture_output=True, text=True)
        if c.returncode:
            sys.exit("iverilog failed:\n" + c.stderr[-1500:])
        r = subprocess.run(["vvp", "-n", str(sim)], capture_output=True, text=True)
        return [l for l in r.stdout.splitlines() if "," in l]


def main(check=False):
    pkg = PKG.read_text()
    alu = enum_names(pkg, "alu_op_t")
    imm = enum_names(pkg, "imm_sel_t")
    wb = enum_names(pkg, "wb_sel_t")
    rows = run_probe()
    head = rows[0].split(",")
    data = [dict(zip(head, r.split(","))) for r in rows[1:]]

    def fmt(r):
        f3 = r["funct3"] if r["f3_used"] == "1" else "—"
        f7 = r["funct7"] if r["f7_used"] == "1" else "—"
        unit = ("mul/div" if r["is_muldiv"] == "1" else
                "CSR" if r["is_csr"] == "1" else
                "load" if r["mem_read"] == "1" else
                "store" if r["mem_write"] == "1" else
                "branch/jump" if r["control_flow"] == "1" else "ALU")
        return (f"| `{r['mnemonic']}` | `{r['opcode']}` | {f3} | {f7} | "
                f"{'yes' if r['legal'] == '1' else '**no**'} | "
                f"{'rd' if r['rf_we'] == '1' else '—'} | "
                f"{alu.get(int(r['alu_op']), r['alu_op'])} | "
                f"{imm.get(int(r['imm_sel']), r['imm_sel'])} | "
                f"{wb.get(int(r['wb_sel']), r['wb_sel'])} | {unit} |")

    good = [r for r in data if not r["mnemonic"].startswith("(")]
    bad = [r for r in data if r["mnemonic"].startswith("(")]

    L = ["# CPU instruction set (RV32IM core)\n",
         "GENERATED by `tools/isa/gen_cpu_isa.py`: every row below is what",
         "`control_unit.sv` DOES when driven with that encoding, recorded by",
         "`tools/isa/isa_probe_cpu.sv`. Do not edit; run the tool.",
         "`make isa-check` fails if this file and the decoder disagree.\n",
         f"{len(good)} encodings swept. Columns after `legal` are the decoder's",
         "own control bundle: which ALU operation it selects, which immediate",
         "format it takes, where the writeback comes from, and which unit runs",
         "the instruction.\n",
         "| instruction | opcode | funct3 | funct7 | legal | writes | ALU op | imm | writeback | unit |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    L += [fmt(r) for r in good]
    L.append("")
    L.append("## Encodings that should be rejected\n")
    L.append("These are probes, not instructions: each is an encoding RV32IM")
    L.append("does not define. What the decoder does with them is a security")
    L.append("property, because a corrupted or fuzzed instruction stream should")
    L.append("trap rather than execute something.\n")
    L.append("| probe | opcode | funct3 | funct7 | legal | decoded as |")
    L.append("|---|---|---|---|---|---|")
    for r in bad:
        unit = ("load" if r["mem_read"] == "1" else "store" if r["mem_write"] == "1"
                else "ALU " + alu.get(int(r["alu_op"]), r["alu_op"]))
        L.append(f"| {r['mnemonic']} | `{r['opcode']}` | {r['funct3']} | "
                 f"{r['funct7']} | {'yes' if r['legal'] == '1' else '**no**'} | "
                 f"{unit if r['legal'] == '1' else 'rejected'} |")
    L.append("")
    accepted = [r for r in bad if r["legal"] == "1"]
    if accepted:
        L.append(f"**{len(accepted)} of {len(bad)} undefined encodings decode as legal.**")
        L.append("The decoder checks the opcode but not every reserved funct")
        L.append("field, so an unallocated encoding executes as its nearest")
        L.append("neighbour instead of raising an illegal-instruction trap. On a")
        L.append("chip whose purpose includes security this is worth a decision:")
        L.append("either tighten the decode, or state that trapping is the")
        L.append("privileged-mode monitor's job and test that it happens.\n")

    text = "\n".join(L) + "\n"
    if check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"DRIFT: {OUT.relative_to(ROOT)} does not match the decoder. "
                  f"Run: python3 tools/isa/gen_cpu_isa.py")
            sys.exit(1)
        print(f"{OUT.relative_to(ROOT)} matches the decoder")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}: {len(good)} instructions, "
              f"{len(bad)} rejection probes, {len(accepted)} of them accepted")


if __name__ == "__main__":
    main(check="--check" in sys.argv)
