#!/usr/bin/env python3
"""
gen_gpu_isa.py -- docs/ISA_GPU.md from gpu_pkg.sv.

The GPU is a 2D tile renderer driven by a command stream, not a shader
engine: its "instruction set" is five opcodes in a 64-bit payload. Parsed
from the package so the table cannot drift.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
PKG = ROOT / "engines/gpu/rtl/gpu_pkg.sv"
OUT = ROOT / "docs/ISA_GPU.md"


def main(check=False):
    if not PKG.exists():
        sys.exit(f"{PKG} is missing")
    t = PKG.read_text()
    cmds = re.findall(r"localparam logic \[7:0\] GPUCMD_(\w+)\s*=\s*8'h([0-9A-Fa-f]+);", t)
    consts = re.findall(r"localparam int (\w+)\s*=\s*(\d+);", t)
    fields = re.findall(r"//\s*\[(\d+):(\d+)\]\s+(\S.*)", t)

    L = ["# GPU command set\n",
         "GENERATED by `tools/isa/gen_gpu_isa.py` from `gpu_pkg.sv`. Do not edit.\n",
         "This is a 2D tile renderer, not a shader engine: work arrives as a",
         "command stream, one 64-bit payload per command. The stream may be",
         "plaintext or encrypted — when encrypted, the payload is recovered as",
         "`payload = enc_payload XOR AES(seed, ctr)[63:0]`, with the counter in",
         "the upper 64 bits of each 128-bit entry.\n",
         "## Payload layout\n",
         "| bits | field |", "|---|---|"]
    for hi, lo, name in fields:
        L.append(f"| [{hi}:{lo}] | {name.strip()} |")
    L += ["", "## Commands\n", "| opcode | name | meaning |", "|---|---|---|"]
    meaning = {"NOP": "do nothing", "CLEAR": "clear the board",
               "SET_CELL": "write the tile at (x, y) with value",
               "WAIT": "stall for `misc` frames", "END": "end of stream"}
    for name, val in cmds:
        L.append(f"| `0x{val.upper()}` | `GPUCMD_{name}` | {meaning.get(name, '')} |")
    if consts:
        L += ["", "## Geometry\n", "| constant | value |", "|---|---|"]
        L += [f"| `{n}` | {v} |" for n, v in consts]
    L.append("")
    text = "\n".join(L)
    if check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"DRIFT: {OUT.relative_to(ROOT)}; run python3 tools/isa/gen_gpu_isa.py")
            sys.exit(1)
        print(f"{OUT.relative_to(ROOT)} matches gpu_pkg.sv")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}: {len(cmds)} commands, {len(fields)} fields")


if __name__ == "__main__":
    main(check="--check" in sys.argv)
